version: "3"

services:
  beanbot:
    build:
      context: "."
      dockerfile: Dockerfile
    volumes:
      - /home/wogong/Dropbox/Server/data/bc:/data
      - ./config.py.docker:/codebase/config.py
    restart: always
