version: "3"

services:
  beanbot:
    build:
      context: "."
      dockerfile: Dockerfile
    volumes:
      - /home/wogong/Dropbox/Server/data/bc:/data
      - ./src/config-docker.py:/codebase/config.py
    restart: always
