version: "3"

services:
  beanbot:
    build:
      context: "."
      dockerfile: Dockerfile
    volumes:
      - /home/wogong/Dropbox/Server/data/bc:/data
      - ./src/.env.docker:/codebase/src/.env
    restart: always
